title: N. Anisa Masruroh
description: "Hey, I'm Anisa! 👋 I'm a Computer Engineering student who loves bringing ideas to life. I don't just stick to the screen—I build full-stack websites, wire up smart IoT systems, and tinker with robotics. Basically, if it involves code, circuits, or moving parts, I'm probably building it."
author: N. Anisa Masruroh
url: "https://anisamsrh.github.io" # Ganti nanti dengan URL GitHub Pages Anda
baseurl: ""

email: "nuranisahidayatulmasruroh@gmail.com"
linkedin: "https://linkedin.com/in/nuranisahm"
github: "https://github.com/anisamsrh"

# Konfigurasi agar Markdown berfungsi dengan baik
markdown: kramdown